### ISSUE TITLE
Use Http_Post without auth

### ISSUE THREAD

**Issue by yhnu** [sassembla/Autoya#12]
I Just Want To Use The Http_XXX,But I Donnt Auth IT

**Comment by sassembla** [comment]
OK, you can use raw HTTP client via Autoya API like this.

https://github.com/sassembla/Autoya/blob/master/Assets/AutoyaSample/8_MainthreadDispatcher/MainthreadDispatchSample.cs#L8

Autoya.HTTP ~ is designed for authenticated http connections only. and it uses Connections.HTTP.HTTPConnection class internally.

how about that?

**Comment by sassembla** [comment]
close until next time!
