### ISSUE TITLE
Scene Assetbundle support available?

### ISSUE THREAD

**Issue by neon-izm** [sassembla/Autoya#31]
SceneAssetbundle (UnityEngine.SceneManagement.Scene) is not have compatible to UnityEngine.Object .

So, how can I load Scene Assetbundle?
https://github.com/sassembla/Autoya/blob/master/Assets/Autoya/AssetBundle/AssetBundleLoader.cs#L260

**Comment by sassembla** [comment]
not yet supported. under implementing..

**Comment by sassembla** [comment]
AssetBundle_LoadScene method is implemented. 595028caf847ea2b2bdc172be33625ada3f2c6e0

**Comment by neon-izm** [comment]
Thanks! I will test it
