### ISSUE TITLE
AutoyaAssetBundleListGenerateProcess error `AssetBundles' does not exist in the namespace `AutoyaFramework'

### ISSUE THREAD

**Issue by SyaoranChang** [sassembla/Autoya#36]
Unity 2018.2.14f1 (64-bit)
Create an empty project then import  Autoya 0.9.0, show error log.

Error log:
Assets/Editor/Autoya.AssetGraphIntegration/AutoyaAssetBundleListGenerateProcess.cs(11,23): error CS0234: The type or namespace name `AssetBundles' does not exist in the namespace `AutoyaFramework'. Are you missing an assembly reference?

**Comment by SyaoranChang** [comment]
I close unity and reopen project.

Error log change to these:
Assets/Autoya/Purchase/LocalPurchaseRouter.cs(114,57): error CS0103: The name `StandardPurchasingModule' does not exist in the current context

Assets/Autoya/Purchase/PurchaseRouter.cs(208,30): error CS0103: The name `AppleAppStore' does not exist in the current context

Assets/Autoya/Purchase/PurchaseRouter.cs(320,57): error CS0103: The name `StandardPurchasingModule' does not exist in the current context

And a warning log:
Assets/Plugins/UnityPurchasing/Editor/UnityIAPInstaller.cs(496,53): warning CS0618: `UnityEditor.PlayerSettings.cloudProjectId' is obsolete: `cloudProjectId is deprecated, use CloudProjectSettings.projectId instead'

**Comment by SyaoranChang** [comment]
http://baba-s.hatenablog.com/entry/2018/03/20/090000
I follow this tutorial, and change .net framework from 3.x to 4.x.,
the error log all gone.
But I change ApiCompatibilityLevel from .NET 4.x to .NET Standard 2.0,
Show new error log:
Assets/Autoya/Encrypt/RIPEMD160.cs(16,33): error CS0246: The type or namespace name `HMACRIPEMD160' could not be found. Are you missing an assembly reference?

**Comment by sassembla** [comment]
the Autoya is designed for .NET 4.x now. You can use older version also. See [Releases](https://github.com/sassembla/Autoya/releases)
