### ISSUE TITLE
AssetBundles Build export to incorrect directory (Windows+ Unity2018.2.14f1) 

### ISSUE THREAD

**Issue by neon-izm** [sassembla/Autoya#37]
## Summary
After AssetBundle built (via AssetGraph) , Autoya copy and export assetbundle caches to ab path ( cf: AssetBundles/main_assets/hogePlatforms/... ).

But my environment , export directory is not expected  above example.
like this.

```
AssetBundles/main_assets/Assets/Editor/AssetGraph-1.4-release/UnityEngine.AssetGraph/Cache/AssetBundles/f22a6572-de57-46ab-beeb-057fa48e8205/Windows
```

## Environment
Windows10Pro(1809) + Unity2018.2.14f1 + Autoya master(head)

Unity target platform (windows, android) is not affection.

##  Steps to Reproduce
1. check out Autoya master branch https://github.com/sassembla/Autoya.git
2. Open Unity2018.2.14(Windows)
3. Open AssetGraph + select "main_assets"
4. ExportDirectory create (AssetBundles/main_assets/)
5. AssetBundle Build.

**Comment by sassembla** [comment]
Thank you for reporting.

 I saw this kind of issue before on Mac, and maybe I've fix this for mac only, not checked in Windows.
Please wait for checking.

**Comment by sassembla** [comment]
related issue appears in bitbucket, https://bitbucket.org/Unity-Technologies/assetbundlegraphtool/pull-requests/16

we will fix this issue when that PR is merged.

**Comment by neon-izm** [comment]
thank you for useful information!

**Comment by sassembla** [comment]
the pull request on the bitbucket repo does not merged yet.
maybe I'll fix it later for Autoya.
please wait.

**Comment by sassembla** [comment]
https://github.com/sassembla/Autoya/tree/0.9.9 fixes this issue.
