### ISSUE TITLE
AssetBundle load impossible Local Paths

### ISSUE THREAD

**Issue by st0326s** [sassembla/Autoya#38]
The following is a local test based on the URL method, but the generation path and the load path do not match.

I'm sorry if you ask the same questions as others,
I want to do a unit test with Autpya, but I'm having trouble with it.

*Reference URL
http://baba-s.hatenablog.com/entry/2018/03/20/090000

After debugging, asset bundles are created in the following path, but the loading destination seems to be different.

***********************
Destination path:
***********************

C: \ Users \ XXXX \ Documents \ Autoya01 / AssetBundles / materials / Assets / Editor / AssetGraph-1.4-release / UnityEngine. AssetGraph / Cache / AssetBundles / c9f2 ebb 0-0451-4368-a4e2-ad5d21e0f4ef / Android / Android. Manifest

***********************
Load path:
***********************
listUrl = file://C: /Users/XXXX/Documents/Autoya01/AssetBundles/materials/Android/1.0.0/materials.json

***********************
 Stack Trace:
***********************
On generation:

rootManifestPath: C: \ Users \ XXXX \ Documents \ Autoya 01 / AssetBundles / materials / Assets / Editors / AssetGraph-1.4-release / Unity Engine. Android.manifest generate list identity: c9f2ebb0-0451-4368-a4e2-ad5d21e0f4ef version: 0
UnityEngine.Debug: Log (Object)
AutoyaAssetBundleListGenerateProcess: DoPostprocess (IEnumerable`1, IEnumerable`1) (at Assets / Editor / Autoya.AssetGraphIntegration / AutoyaAssetBundleListGenerateProcess.cs: 278)
UnityEditor.EditorApplication: Internal_CallDelayFunctions ()

***********************
*During debugging Source

OverridePoints.cs --->
OnAssetBundleListDownloadUrlRequired --->
var url = targetListInfo.listDownloadUrl + "/" + targetListInfo.listIdentity + "/" + AssetBundlesSettings.PLATFORM_STR + "/" + targetListInfo.listVersion + "/";

***********************
*Log

url = file: // C: /Users/XXXX/Documents/Autoya01/AssetBundles/materials/Android/1.0.0/
UnityEngine.Debug: LogError (Object)
AutoyaFramework.Autoya: OnAssetBundleListDownloadUrlRequired (String) (at Assets / Autoya / Backyard / OverridePoints.cs: 379)
AutoyaFramework. <> C: <OnAssetBundleListUrlsRequired> b__151_0 (AssetBundleListInfo) (at Assets / Autoya / Backyard / OverridePoints.cs: 5s)
System.Linq.Enumerable: ToArray (IEnumerable`1)
AutoyaFramework.Autoya: OnAssetBundleListUrlsRequired () (at Assets / Autoya / Backyard / OverridePoints.cs: 508)
AutoyaFramework.Autoya: AssetBundle_DownloadAssetBundleListsIfNeed (Action`1, Action`3, Double) (at Assets / Autoya / Backyard / AssetBundlesImplementation.cs: 455)
Example: OnCLickLoadAssetBundle () (at Assets / Example.cs: 12)
UnityEngine.EventSystems.EventSystem: Update ()

***********************
*Development environment
Unity 2018.3.8f1
Autoya: 0.97

**Comment by sassembla** [comment]
maybe no same issue exists. I'll check it later!
thank you for using Autoya.

**Comment by st0326s** [comment]
・Attach screenshot of output folder

![ExportDirectory](https://user-images.githubusercontent.com/5905837/54801805-f54b9280-4cab-11e9-9e9c-e1ade35abe7f.png)

**Comment by st0326s** [comment]
・Attach a screenshot of folder structure when creating asset bundle

![DirectoryTree_When_Build_From_AssetGraph](https://user-images.githubusercontent.com/5905837/54801940-8c184f00-4cac-11e9-8c99-bf975818220d.png)

**Comment by sassembla** [comment]
very helpful. and so sorry, I missed that this issue is kind of duplicated.
https://github.com/sassembla/Autoya/issues/37#issuecomment-469729455

this is the bug of AssetGraph in Unity 2018.
the export path of AssetGraph in windows is not valid.

**Comment by sassembla** [comment]
and so, the pull request on the bitbucket repo does not merged yet.
maybe I'll fix it later for Autoya.
please wait.

**Comment by st0326s** [comment]
Thank you for your reply and courteous response.

I am waiting for an update

Many people are absent today, so can you borrow a MacBook?
I will ask you next week.

Thank you for closing
