### ISSUE TITLE
SignInWithApple.SignupOrSignin doesn't return ASAuthorizationError.Code

### ISSUE THREAD

**Issue by sfkd-zip** [sassembla/Autoya#49]
ASAuthorizationError.Code includes authorization error reasons. 
By Autoya returns ASAuthorizationError.Code, I can handle the authorization errors.

ASAuthorizationError.Code 
https://developer.apple.com/documentation/authenticationservices/asauthorizationerror/code

**Comment by sassembla** [comment]
looks great suggestion! thank you @ShunFukuda31337 . will be implemented.

**Comment by sassembla** [comment]
contained! in b699d9ac866fe7266bcd280f83947b5985ac2d80. thank you for good request! @ShunFukuda31337
