### ISSUE TITLE
[feature request] URLCaching expiration support.

### ISSUE THREAD

**Issue by JINZO631** [sassembla/Autoya#52]
I want URLCaching to have an expiration date and the feature to delete expired caches.

**Comment by sassembla** [comment]
thank you for request. I'll make it maybe.

**Comment by sassembla** [comment]
adding to 4a13831309927d64c02487431f09fa9c27872fc0.

**Comment by sassembla** [comment]
added to https://github.com/sassembla/Autoya/releases/tag/0.9.17 !
